title: "Atharva Deshmukh Portfolio"
description: "A comprehensive showcase of my work, skills, and experience."
author: "Atharva Deshmukh"
baseurl: "" # Leave blank for root
url: "https://ad2546.github.io" 
theme: minima
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
