# Basic site settings
title: "Atharva Deshmukh Portfolio"
description: "A comprehensive showcase of my work, skills, and experience."
author: "Atharva Deshmukh"
baseurl: "/atharva_portfolio" # Leave blank for GitHub user/organization pages
url: "https://ad2546.github.io" # Replace with your GitHub username

# Theme settings
theme: minima
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap





github:
  is_project_page: false
  owner: "ad2546" # Replace with your GitHub username
  repository: "atharva_portfolio" # Replace with your repository name
